[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "https://sepolia.gateway.tenderly.co"
local = "http://127.0.0.1:8545"
fuji = "https://avalanche-fuji.drpc.org"